# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Ing. Jan Bednář
title: Senior developer
email: ahoj@janbednar.cz
website: www.janbednar.cz

# Dark Mode (true/false/never)
darkmode: true

# Social links
#twitter_username: facespics
github_username:  bedlaj
stackoverflow_username: "8576169"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
# instagram_username: jameswgrant
linkedin_username: jan-bednář-7bb07983
# xing_username: jekyll
# pinterest_username: jekyll
# youtube_username: globalmtb
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
# additional_links:
# - title: itsgoingto.be
#   icon: fas fa-globe
#   url: https://www.itsgoingto.be
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
about_title: O mně
about_profile_image: images/profile.jpeg
about_content: |
  Ahoj! Jmenuji se Honza (přezdívka Bedla) a jsem SW developer.

  Mezi moje specializace patří <mark>JavaEE</mark>, <mark>Apache Camel</mark>, <mark>Spring Boot</mark>, <mark>Quarkus</mark> a integrace včetně designu řešení.

  Umím být součástí celého vývojového cyklu, od quickscanu, nabídky, analýzy, detail designu, přes vývoj, testing, profiling a ladění, CI/CD až po release a i následný L3 support.

  Dokáži pracovat v týmu i sám, agilem i waterfallem.

  Hledám pouze kreativní projekty, které mi budou dávat smysl. Nehledám teplé místečko na údržbě legacy aplikací.
  Hledám projekty na IČO. Nehledám práci na HPP.

  Jsem Apache member a ❤ Open Source.
content:
  - title: Projekty # Title for the section <mark></mark>
    layout: list # Type of content section (list/text)
    content:
      - layout: top-middle
        title: Stream cloud processing IPTV
        sub_title: CGI
        description: |
          Byl jsem součástí agilního týmu, který vyvíjel IPTV stream processing platformu postavenou na mikroservisní architektuře v <mark>Microsoft Azure</mark>. Na projektu jsem byl v rolích Team Leadera, programátora a architekta.
          Aplikace využívá <mark>Apache Kafka</mark>, <mark>Azure Data Explorer</mark>, <mark>Azure Kubernetes</mark>, <mark>Quarkus</mark>, <mark>PostgreSQL</mark>, <mark>Eclipse Vert.X</mark>, <mark>Grafana</mark>, <mark>Azure AD</mark>.
          Provozní monitoring zajišťuje <mark>Eclipse Microprofile Metrics</mark>, který vystavuje <mark>Prometheus</mark> metriky pro <mark>Azure Monitor</mark>. CI/CD proces je zajištěný přes <mark>Azure DevOPS</mark>.
      - layout: top-middle
        title: Stream processing pro BI a Service Assurance
        sub_title: CGI
        description: |
          Byl jsem součástí agilního týmu, který vyvíjel IPTV stream processing platformu postavenou na mikroservisní architektuře v on-prem prostředí. Na projektu jsem byl v rolích Team Leadera a programátora.
          Ekosystém využívá <mark>Apache Kafka</mark>, <mark>Python3</mark>, <mark>Numpy</mark>, <mark>Pandas</mark>, <mark>Kafka Connect</mark> a <mark>Debezium CDC</mark> pro akvizici, normalizaci, transformaci a agregaci dat. Výstupem jsou data v <mark>ElasticSearch</mark>, <mark>MySQL</mark> a <mark>InfluxDB</mark>.
          Aplikace je nasazená v on-prem pomocí <mark>Docker Compose</mark>. Build je přes <mark>Gitlab CI Pipelines</mark>.
          Prezentační logiku pro Service Assurance zajišťují dashboardy v <mark>Grafana</mark>.
          Prezentační logiku pro BI zajišťuje existující Data Warehouse, kterému aplikace poskytuje na SFTP pravidelné extrakty.
      - layout: top-middle
        title: PDS
        sub_title: CGI
        description: |
          Vyvinul jsem aplikaci pro správu a distribuci firmware a balíčků CPE zařízení. Na projektu jsem provedl analýzu řešení, včetně zmapování existujícího komunikačního protokolu a následného vývoje. Aplikace je nasazena v on-prem na <mark>Payara AS</mark> a skládá se z backendu a frontendu.
          Backend vystavuje HTTP endpointy pro CPE a zároveň REST rozhranní pro frontend za využití <mark>Spring Boot</mark>, <mark>Apache Camel</mark>, <mark>EclipseLink</mark>, <mark>Hazelcast</mark>, <mark>MySQL NDB Cluster</mark>. Frontend vystavující uživatelské a administrátorské rozhranní jsem naprogramoval v <mark>AngularJS</mark>.
          Aplikaci jsem následně podle požadavků rozšířil i pro nové typy CPE s odlišným komunikačním rozhranním.
      - layout: top-middle
        title: MAS
        sub_title: CGI
        description: |
          Vyvinul jsem aplikaci pro řízení video enkodéru. Aplikace slouží k přípravě a transkódování video obsahu před nasazením do VOD katalogu. Aplikace má <mark>AngularJS</mark> frontend, obsahující <mark>Shaka Player</mark> a komunikuje se <mark>Spring Boot</mark> backendem pro správu metadat o video souboru. Metadata o jednotlivých stopách a náhledy generuje <mark>Apache Camel</mark> za využití <mark>FFMpeg</mark>.
      - layout: top-middle
        title: PerfTool
        sub_title: CGI
        description: |
          Vyvinul jsem pro IPTV platformu aplikaci pro reálné generování zátěže. Toto usnadnilo projekt stabilizace platformy, protože to umožnilo nasimulovat chování platformy z předchozích výpadků na izolovaném prostředí, nebo mimo televizní špičku. Aplikace pomocí grok patternů parsuje access logy a zákaznické extrakty do <mark>MongoDB</mark>. Následně spouští nad daty transformační vrstvy, které upravují jednotlivé parametry HTTP volání tak, aby byl dodržený požadovaný histogram a délka zátěže, validita volání s ohledem na zadané testovací účty. Technické řešení je pomocí <mark>Apache Camel</mark>, <mark>Spring Boot</mark> a <mark>OKHttp</mark>.
      - layout: top-middle
        title: Validátor VOD obsahu
        sub_title: CGI
        description: |
          Vyvinul jsem nástroj pro automatickou validaci úplnosti nasazení VOD obsahu u IPTV operátora. Aplikace využívá <mark>Spring Boot</mark> a <mark>MySQL</mark>. Generuje report v případě, že nasazení nebylo kompletní, případně chybí některé díly seriálu. Toto ušetřilo nejméně dva dny týdně manuální kontroly, zrychlilo reakční čas a zamezilo pokutám od dodavatele obsahu.
      - layout: top-middle
        title: ActiveMQ Artemis
        sub_title: CGI
        description: |
          Pro Telco operátora jsem ladil JMS Stomp broker ActiveMQ Artemis, který slouží pro vzdálené ovládání CPE. JMS Cluster jsem optimalizoval jak na úrovni konfigurace a JVM, tak na úrovni OS a TCP IP stacku. Pro stejného operátora jsem vyvinul OAuth plugin do ActiveMQ Artemis
      - layout: top-middle
        title: CRM
        sub_title: CGI
        description: |
          Byl jsem součástí týmu, který pro telco operátora vyvíjel backendovou část pro Liferay CRM. Technologie <mark>Spring</mark>, <mark>Wildfly</mark>, <mark>Oracle</mark>
      - layout: top-middle
        title: Billing
        sub_title: CGI
        description: |
          Byl jsem několik let součástí týmu, který pracoval na velkém transformačním projektu billingu. Navrhli jsme a vyvinuli distribuovanou integrační vrstvu mezi provisioningem a billingem, umožňující vykonávání dekompozičních pravidel nad produkty podle logických celků a pluginů na základě BPMN diagramů v Enterprise Architect. Technologie <mark>Wildfly</mark>, <mark>Apache Camel</mark>, <mark>Hibernate</mark>, <mark>Infinispan</mark>, <mark>Oracle</mark>, <mark>JavaFX</mark>, <mark>SOAP</mark>, <mark>JMS</mark>. Aplikace je nasazená ve Wildfly clusteru v doménovém módu. K této aplikaci jsme vyvinuli i několik obslužných aplikací pro správu konfigurací a trasování požadavků.
      - layout: top-middle
        title: Operativní reporting
        sub_title: CGI
        description: |
          Vyvinuli jsme aplikaci pro uživatelsky přívětivé generování ad-hoc reportů, pomocí drag&drop skládání jednotlivých entit a vazeb. Aplikace je vyvinuta pomocí <mark>PHP</mark> a <mark>JQuery</mark>. Aplikační logika validuje a skládá uživatelské modely reportů a následně je dransformuje v SQL dotazy do existujícího datového skladu.
      - layout: top-middle
        title: ETKasa
        link: etkasa.cz
        sub_title: Freelancer
        description: |
          Vyvinul jsem <mark>Android</mark> aplikaci pro evidenci EET tržeb. Aplikace používá <mark>SQLite</mark> a <mark>GreenDAO</mark> pro ukládání tržeb, <mark>SOAP</mark> pro komunikaci s API finanční správy, <mark>ACRA</mark> pro error reporting. Komunikace s tiskárnou probíhá přímou komunikací <mark>POS</mark> příkazů přes bluetooth socket.  K aplikaci jsem vyvinul i <mark>Spring Boot</mark> REST API backend pro správu licencí, aktualizací a monitoring.
      - layout: top-middle
        title: Apache Camel
        link: https://github.com/apache/camel
        # link_text: Project Website
        additional_links:
          - title:  Apache Camel
            icon: fas fa-globe
            url: camel.apache.org/community/team/
        description: |
          Od roku 2019 jsem členem Apache týmu a podílím se na rozvoji Open Source frameworku Apache Camel, který implementuje EIP (Enterprise Integration Patterns)

  - title: Pracovní zkušenosti # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: CGI IT Czech Republic
        link: https://www.cgi.com/ceska-republika/cs
        # link_text: boringcompany.com
        sub_title: Analyst/programmer → System Architect → System Designer
        caption: Březen 2015 - Prosinec 2021
        description: |
          V CGI jsem pracoval převážně na projektech v telco sektoru, ale také ve finančním sektoru. Podílel jsem se na návrhu řešení, nabídkách, implementaci, technologickém rozvoji a L3 supportu. V CGI jsem byl v průběhu času podle potřeby v roli analytika, programátora, architekta a team leadera. V posledních letech jsem participoval i přípravám nabídek, cenových odhadů a v menší míře i business developmentu.
      - layout: left
        title: Materna Communications
        link: https://www.comverga.com/cze/
        # link_text: boringcompany.com
        sub_title: Programátor
        caption: Červenec 2014 - Leden 2015
        description: |
          Pracoval jsem na vývoji Android aplikace pro ČMI s JavaEE Backendem. Spolupracoval jsem na vývoji samoobsluhy pro virtuálního operátora. Zautomatizoval jsem uživatelské testy samoobsluhy, včetně automatizace SMS OTP kódů, pomoci GSM brány. Vyvíjel jsem SPA aplikace pro SMS soutěže, včetně integrace na SMS bránu. Vyvíjel jsem Perl monitorovací scripty pro Nagios a Icinga.

  - title: Vzdělání # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top-middle
        title: Univerzita Hradec Králové
        caption: 2013 - 2016
        sub_title: Aplikovaná Informatika - Ing.
      - layout: top-middle
        title: Univerzita Hradec Králové
        caption: 2010 - 2013
        sub_title: Aplikovaná Informatika - Bc.

  - title: Něco navíc
    layout: list
    content:
      - layout: left
        caption: Aplikační bezpečnost
        description: |
          Orientuji se ve webových útocích a aplikační bezpečnosti. Ve volném čase jsem bug hunter a etický hacker.
      - layout: left
        caption: TCP přenosy a stabilita sítě
        description: |
          Vím, co je TCP retransmission, SYN Flood, socket TIME_WAIT,... Nebojím se použít Wireshark a Tcpdump.
      - layout: left
        caption: Open Source
        description: |
          Fandím Open Source. Když najdu chybu ve veřejném projektu, tak namísto stěžování vytvořím Pull Request.
      - layout: left
        caption: Unit testy
        description: |
          Každý dělá chyby, proto je můj kód krytý unit testy.

# Footer
footer_show_references: false
#references_title: Zákazník má vždycky pravdu, kromě těch případů, kdy nemá.

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
